feat(apps/gtodo-api): add title for todos
gecut/gecut pull request #342
Opened 2023-08-16 16:25 UTC by amir25n

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] All new and existing tests passed.

2023-08-16 22:35 UTC, MM25Zamanian requested changes

2023-08-16 22:35 UTC, MM25Zamanian commented on apps/gtodo-api/src/index.ts
> +  const label = `(${String(++requestCounter).padStart(5,'·')}) ${
چرا کد رو زشت میکنی

2023-08-16 22:35 UTC, MM25Zamanian commented on apps/gtodo-api/src/libs/app.ts
> +            title : true,
پریتیر بزن

2023-08-16 22:35 UTC, MM25Zamanian commented on apps/gtodo-api/src/libs/db.ts
> +  title : string;
پرییتیر

2023-08-16 22:35 UTC, MM25Zamanian commented on apps/gtodo-api/src/libs/db.ts
> +      title : z.string(),
پریییییییتییییییر

2023-08-17 16:16 UTC, amir25n commented on apps/gtodo-api/src/libs/db.ts
> +      title : z.string(),
jesus christ 🤡

2023-10-12 13:29 UTC, closed without merging